[pytest]
DJANGO_SETTINGS_MODULE = steamrf.settings
python_files = test_*.py
python_classes = Test* *Test
python_functions = test_*
addopts = --reuse-db --nomigrations --cov=. --cov-report=term-missing
testpaths = games purchases social users core
