# Generated by Django 5.2.3 on 2025-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameimage',
            name='is_cover',
            field=models.BooleanField(default=False),
        ),
    ]
