# Generated by Django 5.2.3 on 2025-06-28 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameimage_is_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameversion',
            name='file_size_mb',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
