# Generated by Django 5.2.3 on 2025-06-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gameversion_file_size_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='publisher',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
