# Generated by Django 5.2.3 on 2025-06-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_developer_is_active_publisher_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameversion',
            name='download_url',
            field=models.URLField(blank=True),
        ),
    ]
